package com.atharva.auth.core.utils.hash;

public class HashException extends RuntimeException {

    public HashException(String message, Throwable cause) {
        super(message, cause);
    }
}
